---
- name: Build and Deploy todolist-fe 
  hosts: app
  vars:
    ci_cd_namespace: justin-ci-cd
    dev_namespace: justin-dev
    test_namespace: justin-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
